name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory:
          - binary_search
          - quicksort
          
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd ${{ matrix.directory }} 
        cargo build --verbose
    - name: Run tests
      run: |
        cd ${{ matrix.directory }}
        cargo test --verbose
        
